### ISSUE TITLE
Support custom authentication methods

### ISSUE THREAD

**Issue by azmeuk** [migraf/fhir-kindling#50]
Hi. fhir-kindling offer well-know authentication methods, but I have to connect to a FHIR API passing a token in a special header (something different than `authorization`). I would like to define a custom authentication class, similarly to [BearerAuth](https://github.com/migraf/fhir-kindling/blob/362c8af7404bb25b181586eef1c232f11b2717d5/fhir_kindling/fhir_server/auth.py#L61) and pass it to the server. I suggest maybe adding an optional `auth` parameter to the ` FhirServer` class so I can achieve this.

What do you think?

**Comment by migraf** [comment]
Hi, thanks for your interest! 
That seems sensible, though for your case and maybe as a generally useful feature it might be nicer to be able to pass a `headers` dict as parameter to the `FhirServer` class, which can then be used in the instance's requests session.  
Your very welcome to open a PR, otherwise I should get around to it this weekend.

**Comment by migraf** [comment]
Actually I think both would be nice :), headers dict would have to be merged with existing default headers

**Comment by azmeuk** [comment]
Thank you!

**Comment by azmeuk** [comment]
I just tested. This works great!

**Comment by migraf** [comment]
Awesome 😊
